pkgname=lxdm-git

post_install() {
	if ! getent group lxdm > /dev/null; then
		groupadd lxdm
	fi
        if getent group lxdm > /dev/null; then
		chown root:lxdm /etc/lxdm/lxdm.conf
		chown -R root:lxdm /var/lib/lxdm > /dev/null
		chmod +r /etc/lxdm/lxdm.conf
	fi
}

post_upgrade() {
	post_install $1
}

post_remove() {	
	if getent group lxdm > /dev/null; then
		groupdel lxdm
	fi
}

op=$1
shift

$op "$@"
